apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-app
  namespaceSelector:
    matchNames:
      - api-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
